services:
  web:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
    - ./certs:/etc/certs
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    - "443:443"
    networks:
     - network1
networks:
  network1:
    name: mgmt
    external: true
