services:
  web:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
    - ./certs:/etc/certs
    - ./config:/etc/nginx/conf.d
    ports:
    - "80:80"
    - "443:443"
    networks:
     - nginx
networks:
  nginx:
    name: mgmt
    external: true
