# docker-compose.yaml
services:
  jenkins:
    build: .
    privileged: true
    user: root
    ports:
     - 127.0.0.1:50000:50000
    expose:
     - 8080
    container_name: jenkins
    restart: always
    volumes:
     - ./homefolder:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - network1
networks:
  network1:
    name: mgmt
    external: true
