  # docker-compose.yaml
  services:
    jenkins:
      build: .
      privileged: true
      user: root
      ports:
       - 8080:8080
       - 50000:50000
      container_name: jenkins
      volumes:
      - ./homefolder:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock