# docker-compose.yaml
services:
  dind:
    image: docker:dind
    container_name: jenkins-docker
    hostname: docker
    privileged: true
    networks:
     - jenkins
    environment:
     - DOCKER_TLS_CERTDIR=/certs
    volumes:
     - ./homefolder:/var/jenkins_home
     - ./certs:/certs/client
    expose:
     - 2376
    command: --storage-driver=overlay2

  jenkins:
    build: .
    container_name: jenkins-blueocean
    hostname: jenkins
    privileged: true
    user: root
    ports:
     - 127.0.0.1:50000:50000
    expose:
     - 8080
    environment:
     - DOCKER_HOST=tcp://docker:2376
     - DOCKER_CERT_PATH=/certs/client
     - DOCKER_TLS_VERIFY=0
    restart: always
    volumes:
     - ./homefolder:/var/jenkins_home
     - ./certs:/certs/client:ro
    networks:
     - jenkins
networks:
  jenkins:
    name: mgmt
    external: true
