{
 "title": "Loki Kubernetes Logs",
 "description": "Logs collected from Kubernetes, stored in Loki",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "ds", "query": "loki" },
   { "name": "query", "label": "Search Query word" },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "app",
    "label": "app",
    "query": {}
   },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "stream",
    "query": {}
   },
   {
    "name": "level",
    "label": "Log level",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Log Distribution View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ds" },
  {
   "title": "Total logs by time / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({stream=~\"stdout|stderr\", namespace=~\"$namespace\", stream=~\"$stream\", app=~\"$app\", container=~\"$container\", level=~\"$level\"} |~ \"(?i)$query\" [$__interval]))",
     "legendFormat": "Log count"
    }
   ]
  },
  {
   "title": "Total log by level / $__interval",
   "type": "timeseries",
   "description": "level percentile",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({stream=~\"stdout|stderr\",app=~\"$app\", namespace=~\"$namespace\", stream=~\"$stream\", level=~\"$level\"} |~ \"(?i)$query\" [$__interval]))"
    }
   ]
  },
  {
   "title": "total log line by app / $__interval",
   "type": "timeseries",
   "description": "Logs by by app group",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({stream=~\"stdout|stderr\", app=~\"$app\", namespace=~\"$namespace\", stream=~\"$stream\", level=~\"$level\"} |~ \"(?i)$query\" [$__interval])) by (app)"
    }
   ]
  },
  { "title": "Log Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "📃Log Content",
   "type": "logs",
   "description": "Logs from services running in Kubernetes",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", stream=~\"$stream\", app =~\"$app\", container=~\"$container\", level=~\"$level\"} |~ \"(?i)$query\""
    }
   ]
  }
 ]
}