route:
  receiver: 'telegram-receiver'
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'telegram-receiver'
    telegram_configs:
      - send_resolved: true
        bot_token:
        chat_id: